title: Brain Blog
email: your-email@example.com
description: 'Your blog description'
baseurl: "/brain-blog" 
url: "https://elixd.github.io" 
github_username:  elixd

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
